version: '3.8'
services:
  db:
    image: postgres:14.5-alpine
    ports:
      - '5432:5432'
    environment:
      # username: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: link-shortener
    volumes:
      - postgresql_data:/var/lib/postgresql/data

volumes:
  postgresql_data:
